### ISSUE TITLE
Please use readthedocs.org instead of shipping prebuilt documentation in the repository

### ISSUE THREAD

**Issue by eriol** [gmrandazzo/libscientific#3]
Hi! Instead of shipping prebuilt documentation inside the repository¹, hosting it on https://readthedocs.org/ would have the with following advantage:
1. versioning
2. search
3. multiple formats
4. auto-generated on push.

¹ maybe it's used to show it at https://gmrandazzo.github.io/libscientific/?

**Comment by gmrandazzo** [comment]
Hi Eriol,

Thank you for the advice.
Yes. It the prebuilt documentation is used in https://gmrandazzo.github.io/libscientific/. Of course, it makes sense to move it on readthedocs. From now the upstream version will have the documentation to readthedocs.org. 

Bests
